import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: [ "latin" ],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: [ "latin" ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ({ children })
{
  return (
    <html lang="en">
      <body
        className={`${ geistSans.variable } ${ geistMono.variable } antialiased bg-white`}
      >
        <div className="md:flex  min-h-screen bg-white text-gray-900">
          <Sidebar />
          <div className="w-full">
            {children}
         </div>
        </div>
      </body>
    </html>
  );
}
